### ISSUE TITLE
Quantile-based threshold 

### ISSUE THREAD

**Issue by lingminhao** [shimlab/BLAZE#6]
Hi @youyupei , may I know how do you select the count threshold when selecting the barcodes into the whitelist?

**Comment by youyupei** [comment]
Hi @lingminhao，

The threshold is given as follows:
For a given expected number of recovered cells, denoted by 𝑁 (specified using `--expect-cells`),  we first calculate the 95th percentile of the top N counts (let's say it's  𝑐 ). Then, we use 0.05 × 𝑐 as the threshold. 

This is quite similar to earlier versions of CellRanger. However, CellRanger used the 99th percentile of top N UMI counts and the  0.1 × 𝑐 as the threshold. We relaxed the threshold a little bit because we are counting high-quality putative barcodes, which could be more variable than the UMI counts.

I hope it makes sense, feel free to let me know if it doesn't.

Regards,
Yupei

**Comment by lingminhao** [comment]
Hi @youyupei , let me just reiterate it by giving an example: 
Say if my expected number of cells is 500, then c will be the count of the 475th cell, say 3500. Then 0.05 * 3500 = 175 will be the threshold, which mean any cells with counts >= 175 will be selected. Am I correct?
